"""
This is the main script for the script.
"""
if __name__ == "__main__":
    print("Hello worlds")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldsssss")
    print("Hello worldly beings")

